-- phpMyAdmin SQL Dump
-- version 5.3.0-dev+20220609.11e34a6fec
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 19 Jun 2022 pada 15.41
-- Versi server: 10.4.24-MariaDB
-- Versi PHP: 8.1.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project_film`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `film`
--

CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `genre` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `release_date` date NOT NULL,
  `vote_count` int(11) NOT NULL,
  `vote_average` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `film`
--

INSERT INTO `film` (`id`, `title`, `genre`, `image`, `description`, `release_date`, `vote_count`, `vote_average`) VALUES
(121, 'Marvel Infinity War', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg', 'Karena Avengers dan sekutunya terus melindungi dunia dari ancaman yang terlalu besar untuk ditangani oleh seorang pahlawan, bahaya baru telah muncul dari bayangan kosmik: Thanos. Seorang lalim penghujatan intergalaksi, tujuannya adalah untuk mengumpulkan semua enam Batu Infinity, artefak kekuatan yang tak terbayangkan, dan menggunakannya untuk menimbulkan kehendak memutar pada semua realitas. Segala sesuatu yang telah diperjuangkan oleh Avengers telah berkembang hingga saat ini - nasib Bumi dan keberadaannya sendiri tidak pernah lebih pasti.\r\n\r\n<b><i>\r\nPemain : Robert Downey Jr</b>', '2018-04-25', 8901, 9),
(122, 'The Avengers', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/kRK4AKBQEWcmIF9lvkt5qxSwQ28.jpg', 'Ketika musuh yang tak terduga muncul, mengancam keselamatan dan keamanan dunia, Nick Fury, direktur Badan Perdamaian Internasional, dikenal sebagai S.H.I.E.L.D. , membutuhkan tim untuk menyelamatkan dunia dari bencana. Usaha perekrutan pun dimulai Iron Man, Captain America, Hulk, Thor, Black Widow dan Hawkeye dikumpulkan untuk menaklukkan Dewa Kehancuran, Loki, dalam usahanya menghancurkan bumi. Dengan semua gabungan kekuatan, tugas nampak lebih mudah. Namun kenyatannya tidak demikian! Para pahlawan super justru saling melawan satu sama lain Hulk melawan Captain America, siapa yang akan menang? Apakah Iron Man dapat mengalahkan kekuatan super milik Thor? Bagaimana para pahlawan super ini secara bersama-sama menghadapi bencana, melindungi masyarakat dan yang terpenting, bertahan hidup?\r\n\r\n<b><i>\r\nPemain : Robert Downey Jr</b>', '2015-05-04', 2001, 5),
(123, 'Sonic the Hedgehog 2', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg', 'Alur cerita film Sonic the Hedgehog 2 bermula ketika Sonic menetap di Green Hills. Ia memutuskan menetap di sana agar bisa merasakan lebih banyak kebebasan. Ditambah lagi, Tom dan Maddie setuju untuk meninggalakannya di rumah ketika mereka pergi untuk berlibur. Namun sayangnya, tidak lama setelah mereka pergi Dr. Robotnik sang musuh bubuyutan si landak biru itu kembali ke bumi. Kali ini Dr. Robotnik datang dengan pasukan baru, Knuckles. Tujuan mereka datang kembali adalah untuk mencari Master Emerald yang memiliki kekuatan super. Kekuatan super itu bisa membangun dan menghancurkan peradaban di bumi. Atas hal ini, Sonic pun mencari strategi agar bisa menggagalkan rencara Dr. Robotnik. Strategi yang dilakukan oleh Sonic ialah bekerjasama dengan sahabatnya, Tails. Kemudian bersama dengan Tails, Sonic memulai perjalanan untuk menemukan Master Emerald. Semua itu dilakukan dengan cepat, sebelum Master Emerald jatuh ke tangan yang salah.\r\n\r\n<b>\r\nPemain : James Marsden,Ben Schwartz,\r\nTika Sumpter</b>', '2022-08-04', 3451, 8),
(124, 'Iron Man', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/75CyGj7XjM3duSh0ykuX9v4GtMD.jpg', 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.\r\n\r\n<b><i>\r\nPemain : Robert Downey Jr</b>', '2008-04-30', 1211, 7),
(125, 'Iron Man 2 ', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uMvRuoptuLufj1KZDc0fptYA8yZ.jpg', 'With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James \'Rhodey\' Rhodes at his side, must forge new alliances – and confront powerful enemies.\r\n\r\n\r\n<b><i>\r\nPemain : Robert Downey Jr.,Scarlett Johansson,Gwyneth Paltrow,Don Cheadle,Samuel L. Jackson</b>\r\n', '2010-05-07', 381, 7),
(126, 'Thor (2011)', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/jWnbuXuzMIl3FDIs0qY9ZdDPxCl.jpg', 'Melawan kehedak Ayahnya Odin, Sang Perkasa Thor – Dewa pejuang yang kuat namun sombong – dengan ceroboh menyalakan kembali perang kuno. Thor dibuang ke Bumi dan dipaksa untuk hidup di antara manusia sebagai hukuman. Begitu tiba di sini, Thor belajar apa yang diperlukan untuk menjadi pahlawan sejati ketika penjahat paling berbahaya di dunianya mengirimkan pasukan tergelap Asgard untuk menyerang Bumi.\r\n\r\n<b>\r\nPemain : Chris Hemsworth,Natalie Portman,Tom Hiddleston </b>\r\n', '2011-11-03', 8229, 7),
(127, 'Thor: Ragnarok', '7', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/8hnNdUFlUkjPWxKDyiE4Kn8h7Q5.jpg', 'Setelah mendengar muncul berbagai permasalahan di tempat asalnya, Thor (Chris Hemsworth) pulang ke Asgard. Ia kehilangan senjata andalannya dan terperangkap dalam sebuah penjara. Namun saat itu juga ia harus berlomba dengan waktu untuk menghentikan ‘Ragnarok’ dengan melawan Hela, musuh kuat yang ingin menghancurkan Asgard.\r\n\r\n<b>\r\nPemain : Chris Hemsworth,Tom Hiddleston,Cate Blanchett\r\n</b>', '2022-04-07', 1474, 7),
(128, 'Eternals', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/lFByFSLV5WDJEv3KabbdAF959F2.jpg', 'The Eternals adalah tim alien kuno yang telah hidup di Bumi secara rahasia selama ribuan tahun. Ketika sebuah tragedi tak terduga memaksa mereka keluar dari bayang-bayang, mereka dipaksa untuk bersatu kembali melawan musuh paling kuno umat manusia, Deviants.\r\n\r\n<b>\r\nPemain : Gemma Chan,Richard Madden\r\n</b> ', '2022-05-04', 2249, 7),
(129, 'Shang-Chi dan Legenda Sepuluh Cincin', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg', 'Shang-Chi harus menghadapi masa lalu yang dia pikir telah di lupakan dan menghadapi ayahnya, pimpinan organisasi Sepuluh Cincin yang berbahaya.\r\n\r\n<b>\r\nPemain : Simu Liu,Tony Leung Chiu-wai\r\n</b> ', '2021-12-15', 13459, 8),
(130, 'The Adam Project', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg', 'Mengisahkan tentang perjalanan waktu. Adam Reed adalah seorang pilot tempur tahun 2050. Saat melakukan perjalanan waktu untuk menyelamatkan istrinya di tahun 2018, Adam justru terdampar di tahun 2022. Demi menyelamatkan masa depan, akhirnya Adam Reed bekerjasama dengan dirinya di tahun 2022 yang masih berusia 12 tahun. Film ini menceritakan petualangan Adam dengan dirinya sendiri di tahun 2022. Kunci dari misi Adam adalah di tahun 2018, namun dirinya justru terjebak di tahun 2022. Akankah Adam berhasil pergi ke tahun 2018 Dan menyelamatkan istrinya?\r\n\r\n<b>\r\nPemain : Ryan Reynolds,Walker Scobell\r\n</b> ', '2022-01-28', 120, 6),
(131, 'Mortal Kombat', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg', 'Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung\'s best warrior, Sub-Zero, seeks out and trains with Earth\'s greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.\r\n\r\n<b>\r\nPemain :Lewis Tan,Jessica McNamee\r\n</b>\r\n', '2022-02-10', 2387, 7),
(133, 'Titanic', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', '101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic\'s departure through to its death—on its first and last voyage—on April 15, 1912.\r\n\r\n<b>\r\nPemain : Leonardo DiCaprio,Kate Winslet\r\n</b> ', '2022-03-10', 2432, 8),
(134, 'The In Between', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7RcyjraM1cB1Uxy2W9ZWrab4KCw.jpg', 'After surviving a car accident that took the life of her boyfriend, a teenage girl believes he\'s attempting to reconnect with her from the after world.\r\n\r\n<b>\r\nPemain : Joey King,Kyle Allen\r\n</b> ', '2022-04-21', 52, 5),
(135, 'Redeeming Love', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/z8VpsTdIjBhdeGeNEsHFwz6MJXp.jpg', 'A retelling of the biblical book of Hosea set against the backdrop of the California Gold Rush of 1850.\r\n\r\n<b>\r\nPemain : Logan Marshall-Green,Abigail Cowen\r\n</b>', '2022-03-04', 59, 6),
(136, 'A Perfect Pairing', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/h65lLhYEfRGOWVZzwX9n7vYOixf.jpg', 'To land a major client, an LA wine exec travels to an Australian sheep station, where she signs on as a ranch hand and hits it off with a rugged local.\r\n\r\n<b>\r\nPemain : Victoria Justice,Adam Demos\r\n</b> ', '2022-03-17', 620, 8),
(137, 'After Ever Happy', '8', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/vWLyXOFm1C3gnS8ksfqi7gwkijn.jpg', 'As a shocking truth about a couple\'s families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.\r\n\r\n<b>\r\nPemain : Josephine Langford,Hero Fiennes Tiffin\r\n</b> ', '2022-03-10', 309, 7),
(139, 'Real Steel', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/4GIeI5K5YdDUkR3mNQBoScpSFEf.jpg', 'Charlie Kenton is a washed-up fighter who retired from the ring when robots took over the sport. After his robot is trashed, he reluctantly teams up with his estranged son to rebuild and train an unlikely contender.\r\n\r\n<b>\r\nPemain : Hugh Jackman,Dakota Goyo,Evangeline Lilly <b/>\r\n\r\n', '2011-10-28', 5042, 7),
(140, 'Space Jam: A New Legacy', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg', 'When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.\'s digitized champions on the court. It\'s Tunes versus Goons in the highest-stakes challenge of his life.\r\n\r\n<b>\r\nPemain : Lebron James </b>', '2021-07-16', 5101, 7),
(141, 'Boyka: Undisputed IV', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/7QGdIJWWTkPhVjpQ0zA6z69khod.jpg\r\n', 'In the fourth installment of the fighting franchise, Boyka is shooting for the big leagues when an accidental death in the ring makes him question everything he stands for. When he finds out the wife of the man he accidentally killed is in trouble, Boyka offers to fight in a series of impossible battles to free her from a life of servitude.\r\n\r\n<b>\r\nPemain : Scott Adkins,Teodora Duhovnikova,Alon Aboutboul</b>', '2016-08-01', 1252, 7),
(142, 'Creed', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/iBq4od6j1ZAvDVO7hwmHT2Xf2Bt.jpg', 'The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.\r\n\r\n<b>\r\nPemain : Michael B. Jordan,Sylvester Stallone,Tessa Thompson</b>', '2015-11-25', 2253, 8),
(143, 'Creed II', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/qPQFWrLoQYyGxmeBgmpX901Q0mF.jpg', 'Between personal obligations and training for his next big fight against an opponent with ties to his family\'s past, Adonis Creed is up against the challenge of his life.\r\n\r\n<b>\r\nPemain : Pemain : Michael B. Jordan,Sylvester Stallone,Tessa Thompson </b>\r\n', '2018-04-11', 7865, 9),
(144, 'Home Team', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/xdPdVJGIQjuVhK7SeK5fpjuc1bu.jpg', 'Dua tahun setelah pelatih kepala NFL Sean Payton diskors, dia kembali ke kampung halamannya dan menemukan dirinya terhubung kembali dengan putranya yang berusia 12 tahun dengan melatih tim sepak bola Pop Warner-nya.\r\n\r\n<b>\r\nPemain : Kevin James,Rob Schneider\r\nTaylor Lautner</b>', '2022-01-28', 15, 6),
(145, 'Southpaw', '1', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/r6QlMEQGNvM0YpbN04qhx5xdMiQ.jpg', 'Billy \"The Great\" Hope, the reigning junior middleweight boxing champion, has an impressive career, a loving wife and daughter, and a lavish lifestyle. However, when tragedy strikes, Billy hits rock bottom, losing his family, his house and his manager. He soon finds an unlikely savior in Tick Willis, a former fighter who trains the city\'s toughest amateur boxers. With his future on the line, Hope fights to reclaim the trust of those he loves the most.\r\n\r\n<b>\r\nPemain : Jake Gyllenhaal,Rachel McAdams,Forest Whitaker\r\n</b>', '2015-07-24', 966, 8),
(146, 'Pirates of the Caribbean: On Stranger Tides', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/keGfSvCmYj7CvdRx36OdVrAEibE.jpg', 'Captain Jack Sparrow crosses paths with a woman from his past, and he\'s not sure if it\'s love -- or if she\'s a ruthless con artist who\'s using him to find the fabled Fountain of Youth. When she forces him aboard the Queen Anne\'s Revenge, the ship of the formidable pirate Blackbeard, Jack finds himself on an unexpected adventure in which he doesn\'t know who to fear more: Blackbeard or the woman from his past.\r\n\r\n<b>\r\nPemain :Johnny Depp,Penélope Cruz\r\n</b>', '2016-10-25', 19153, 7),
(147, 'Avatar', '6', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'Pada abad ke-22, seorang Marinir lumpuh dikirim ke Pandora bulan pada misi yang unik, tetapi menjadi terpecah antara mengikuti perintah dan melindungi peradaban alien.\r\n\r\n<b> \r\nPemain : Sam Worthington,Zoe Saldana\r\n</b> ', '2021-11-24', 6672, 8),
(151, 'The Boss Baby: Bisnis Keluarga', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg', 'Saudara-saudara Templeton, tim, boss Baby-nya, dan adik kecil Ted telah menjadi dewasa dan menjauh satu sama lain. Tetapi seorang bos bayi baru dengan pendekatan mutakhir dan sikap yang dapat dilakukan akan menyatukan mereka kembali dan menginspirasi bisnis keluarga baru.\r\n\r\n<b>\r\nPemain : Alec Baldwin,James Marsden\r\n</b>', '2021-07-02', 2464, 8),
(152, 'Minions: The Rise of Gru', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/wKiOkZTN9lUUUNZLmtnwubZYONg.jpg', 'A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.\r\n\r\n<b>\r\nPemain : Steve Carell,Pierre Coffin\r\n</b>', '2022-07-01', 28, 7),
(153, 'BORUTO -NARUTO THE MOVIE', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1k6iwC4KaPvTBt1JuaqXy3noZRY.jpg', 'The spirited Boruto Uzumaki, son of Seventh Hokage Naruto, is a skilled ninja who possesses the same brashness and passion his father once had. However, the constant absence of his father, who is busy with his Hokage duties, puts a damper on Boruto\'s fire. He ends up meeting his father\'s friend Sasuke, and requests to become... his apprentice!? The curtain on the story of the new generation rises!\r\n\r\n<b>\r\nPemain : Yuko Sanpei,Kokoro Kikuchi\r\n</b>', '2015-08-07', 190, 8),
(156, 'Coco', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg', 'Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel\'s family history.\r\n\r\n<b>\r\nPemain : Anthony Gonzalez,Gael García Bernal\r\n</b>', '2022-06-09', 35, 7),
(157, 'Tom & Jerry', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/yMoMlJo2msoVwmuf6k1C78MrB3H.jpg', 'Tom si kucing dan Jerry si tikus diusir dari rumah mereka dan pindah ke hotel mewah di New York, di mana seorang karyawan yang suka berkelahi bernama Kayla akan kehilangan pekerjaannya jika dia tidak bisa mengusir Jerry sebelum pernikahan kelas atas di hotel. Solusinya? Mempekerjakan Tom untuk menyingkirkan tikus sial itu.\r\n\r\n<b>\r\nPemain : Chloë Grace Moretz,Michael Peña\r\n</b>', '2022-02-25', 969, 7),
(158, 'The Lion King', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/b7oicyn6023fEIC9fqaoftEJfwt.jpg', 'A young lion prince is cast out of his pride by his cruel uncle, who claims he killed his father. While the uncle rules with an iron paw, the prince grows up beyond the Savannah, living by a philosophy: No worries for the rest of your days. But when his past comes to haunt him, the young prince must decide his fate: Will he remain an outcast or face his demons and become what he needs to be?\r\n\r\n<b>\r\nPemain :Matthew Broderick,James Earl Jones\r\n</b> ', '2022-05-11', 184, 8),
(159, 'Shrek 2', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg', 'Shrek, Fiona and Donkey set off to Far, Far Away to meet Fiona\'s mother and father. But not everyone is happy. Shrek and the King find it hard to get along, and there\'s tension in the marriage. The fairy godmother discovers that Shrek has married Fiona instead of her Son Prince Charming and sets about destroying their marriage.\r\n\r\n<b>\r\nPemain : Mike Myers,Eddie Murphy\r\n</b>', '2022-02-16', 29, 7),
(160, 'Ratatouille', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/npHNjldbeTHdKKw28bJKs7lzqzj.jpg', 'Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy culinary masterpieces to his heart\'s delight. The only problem is, Remy is a rat. When he winds up in the sewer beneath one of Paris\' finest restaurants, the rodent gourmet finds himself ideally placed to realize his dream.\r\n\r\n<b>\r\nPemain : Patton Oswalt,\r\nIan Holm\r\n</b>', '2021-07-02', 350, 8),
(161, 'Fireheart', '5', 'https://image.tmdb.org/t/p/w200/hepwOZWJNUmLzB68gKYEdEJAaD3.jpg', 'The film explores the world of firefighters in 1920s New York City and tells the story of a 16-year-old girl who will have to become a hero in order to save her city.\r\n\r\n<b>\r\nPemain : Olivia Cooke,Kenneth Branagh\r\n</b>', '2022-01-16', 73, 7),
(163, 'Frozen', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/kgwjIb2JDHRhNk13lmSxiClFjVk.jpg', 'Young princess Anna of Arendelle dreams about finding true love at her sister Elsa’s coronation. Fate takes her on a dangerous journey in an attempt to end the eternal winter that has fallen over the kingdom. She\'s accompanied by ice delivery man Kristoff, his reindeer Sven, and snowman Olaf. On an adventure where she will find out what friendship, courage, family, and true love really means.\r\n\r\n<b>\r\nPemain : Kristen Bell,Idina Menzel\r\n</b> ', '2015-06-06', 18093, 7),
(165, 'Big Hero 6', '5', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/2mxS4wUimwlLmI1xp6QW6NSU361.jpg', 'Ikatan khusus yang berkembang antara robot tiup Baymax ukuran plus, dan Hiro Hamada yang luar biasa, yang bekerja sama dengan sekelompok teman untuk membentuk sekelompok pahlawan teknologi tinggi.\r\n\r\n<b>\r\nPemain : Scott Adsit,Ryan Potter\r\n</b>', '2022-01-28', 1205, 7),
(167, 'Turning Red', '4', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg', 'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.\r\n\r\n<b>\r\nPemain : Rosalie Chiang,Sandra Oh\r\n</b>', '2021-10-03', 7465, 7),
(168, 'Luca', '4', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/8tABCBpzu3mZbzMB3sRzMEHEvJi.jpg', 'Sinopsis Luca menceritakan tentang persahabatan antara Luca Paguro (Jacob Tremblay) anak laki-laki usia 13 tahun dengan sahabat barunya, Alberto Scorfano (Jack Dylan Grazer) monster laut remaja yang sangat suka melakukan hal baru.\r\n\r\n<b>\r\nPemain : Jacob Tremblay,Jack Dylan Grazer\r\n</b>', '2021-06-17', 215, 6),
(169, 'Toy Story', '4', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', 'Led by Woody, Andy\'s toys live happily in his room until Andy\'s birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy\'s heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.\r\n\r\n<b>\r\nPemain : Tom Hanks,Tim Allen\r\n</b>', '1995-11-22', 1, 2),
(170, 'Toy Story 2 ', '4', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/eVGu0zsezaSCuN67zgNhzjeNI9Z.jpg', 'Andy heads off to Cowboy Camp, leaving his toys to their own devices. Things shift into high gear when an obsessive toy collector named Al McWhiggen, owner of Al\'s Toy Barn kidnaps Woody. Andy\'s toys mount a daring rescue mission, Buzz Lightyear meets his match and Woody has to decide where he and his heart truly belong.\r\n\r\n<b>\r\nPemain : Tom Hanks,\r\nTim Allen\r\n</b>', '1999-11-24', 7, 5),
(171, 'Venom', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/bURIWlkMbzT8RdpemzCmQECo2Uh.jpg', 'Seorang jurnalis, Eddie Brock (Tom Hardy) ingin melakukan sebuah investasi kasus terhadap penemuan yang dipimpin oleh Dr. Carlton Drake (Riz Ahmed). Karena investigasinya, Eddie mengunjungi lab milik Dr. Calrlton Drake. Semuanya ditujukan untuk membuktikan bahwa Dr. Carlton Drake sedang sedang melakukan tindakan jahat menggunakan Symbiote. Namun, sial bagi Eddie, organisme hidup ini masuk ke dalam tubuhnya. Eddie menemukan kekuatan super dalam dirinya yang mampu mengendalikan semua hal yang ia lakukan.\r\n\r\n<b>\r\nPemain :Tom Hardy,Michelle Williams </b>', '2018-10-05', 2832, 7),
(172, 'Venom: Let There Be Carnage', '3', 'https://image.tmdb.org/t/p/w200/1MJNcPZy46hIy2CmSqOeru0yr5C.jpg', 'Venom kembali beraksi ketika pembunuh berantai terkenal Cletus Cassidy menjadi pembantaian yang kejam.\r\n\r\n<b>\r\nPemain : Tom Hardy,Woody Harrelson\r\n</b>', '2021-09-30', 5812, 7),
(173, 'Moon Knight', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/vKDUmKO6F9bSKKyHhg7YGbgcEeF.jpg', 'Steven Grant menemukan bahwa dia telah diberikan kekuatan dewa bulan Mesir. Tapi dia segera menemukan bahwa kekuatan baru ini dapat menjadi berkat dan kutukan untuk hidupnya yang bermasalah.\r\n\r\n<b>\r\nPemain : Oscar Isaac\r\n</b>', '2022-06-06', 9922, 7),
(174, 'The Boys ', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg', 'Sekelompok penjaga yang dikenal secara informal sebagai \"The Boys\" berangkat untuk menjatuhkan superhero yang korup dengan tidak lebih dari grit kerah biru dan kesediaan untuk melawan yang kotor.\r\n\r\n<b>\r\nPemain :Karl Urban,Jack Quaid </b>', '2022-06-01', 2820, 8),
(175, 'Peaky Blinders ', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/bGZn5RVzMMXju4ev7xbl1aLdXqq.jpg', 'Sebuah epik keluarga gangster berlatar di Birmingham, Inggris pada tahun 1919 dan berpusat pada sebuah geng yang menjahit pisau silet di puncak topi mereka, dan bos mereka yang garang Tommy Shelby, yang bermaksud untuk naik ke dunia.\r\n\r\n<b>\r\nPemain : Cillian Murphy,\r\nPaul Anderson </b>', '2022-02-27', 427, 6),
(176, 'Stranger Things', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uKYUR8GPkKRCksczYDJb3pwZauo.jpg', 'Ketika seorang bocah lelaki menghilang, sebuah kota kecil mengungkap misteri yang melibatkan eksperimen rahasia, kekuatan gaib yang menakutkan, dan seorang gadis kecil yang aneh.\r\n\r\n<b>\r\nPemain : Millie Bobby Brown,\r\nFinn Wolfhard </b>\r\n', '2022-05-27', 5121, 8),
(177, 'Ms Marvel', '2', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/cdkyMYdu8ao26XOBvilNzLneUg1.jpg', 'Seorang siswa yang hebat, gamer yang rajin, dan penulis fan-fic yang rakus, Kamala Khan memiliki ketertarikan khusus pada pahlawan super, terutama Captain Marvel. Namun, dia berjuang untuk menyesuaikan diri di rumah dan di sekolah — yaitu, sampai dia mendapatkan kekuatan super seperti pahlawan yang selalu dia hormati. Hidup lebih mudah dengan kekuatan super, bukan?\r\n\r\n<b>\r\nPemain : Iman Vellani,Matt Lintz\r\n</b>', '2022-06-01', 9331, 6),
(178, 'Doctor Strange', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg', 'Hidup Stephen Vincent Strange (Benedict Cumberbatch), seorang doktor bedah yang pintar namun sombong, mendadak berubah drastis. Sebuah kecelakaan mobil membuat kemampuan tangannya menjadi sangat terbatas. Bertekad untuk menyembuhkan kondisinya, ia pun berpetualang mencari obat untuk memulihkan tangannya. Perjalanan tersebut mempertemukan sang doktor bedah dengan penyihir bernama The Ancient One (Tilda Swinton), yang kemudian mengangkat Strange menjadi murid, dengan tujuan menjadikan ia sebagai pelindung alam manusia. Kali ini Strange harus mengesampingkan egonya, dan menggunakan segala kemampuannya untuk menjadi perantara antara dimensi manusia dan dimensi lain.\r\n\r\n<b>\r\nPemain : Benedict Cumberbatch,Chiwetel Ejiofor\r\n</b>', '2016-11-06', 4421, 6),
(179, 'Spider-Man: No Way Home', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'Peter Parker menghadapi masalah besar. Hal ini terjadi setelah identitasnya sebagai Spiderman terungkap. Dengan kepergian Tony Stark, Peter Parker pun harus meminta bantuan Doctor Strange agar semua orang bisa melupakan identitasnya sebagai manusia laba-laba.\r\n\r\n<b>\r\nPemain : Tom Holland,Zendaya\r\n</b>', '2021-12-17', 27, 8),
(180, 'The Batman', '3', 'https://www.themoviedb.org/t/p/w300_and_h450_bestv2/3VFI3zbuNhXzx7dIbYdmvBLekyB.jpg', 'Ketika seorang pembunuh berantai sadis mulai membunuh tokoh-tokoh politik penting di Gotham, Batman terpaksa menyelidiki korupsi tersembunyi di kota itu dan mempertanyakan keterlibatan keluarganya.\r\n\r\n<b>\r\nPemain :Robert Pattinson,Zoë Kravitz\r\n</b>', '2022-03-02', 2531, 8);

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `film`
--
ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=181;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;



